# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltexam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poked', to='beltexam.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker', to='beltexam.User')),
            ],
        ),
    ]
